steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStack'
    browserstackLocal: true
    bsLocalOptions: 'forceLocal: true'
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
